/// ensure_macos_sidecar_placeholder: `tauri.macos.conf.json` lists
/// `binaries/smind` as an `externalBin`, and tauri-build refuses to build
/// when `binaries/smind-<target-triple>` is missing -- which would break a
/// plain `cargo test`/`cargo clippy` on a Mac that never ran
/// `task desktop:mac`. Debug builds get an empty placeholder (the install
/// path rejects an empty bundled binary with a clear error); release
/// builds never do, so a real bundle can't silently ship without a daemon.
fn ensure_macos_sidecar_placeholder() {
    let is_macos = std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("macos");
    let is_release = std::env::var("PROFILE").as_deref() == Ok("release");
    if !is_macos || is_release {
        return;
    }
    let target = std::env::var("TARGET").expect("cargo sets TARGET for build scripts");
    let path = std::path::PathBuf::from("binaries").join(format!("smind-{target}"));
    if path.exists() {
        return;
    }
    std::fs::create_dir_all("binaries").expect("smind desktop: create binaries/");
    std::fs::write(&path, b"").expect("smind desktop: write sidecar placeholder");
}

fn main() {
    ensure_macos_sidecar_placeholder();
    // AC5/AC6: the connection-picker/open-external commands get
    // autogenerated `allow-*`/`deny-*` permissions
    // (desktop/src-tauri/permissions/autogenerated/, gitignored, rebuilt
    // every build), referenced -- unprefixed, since they're app
    // commands, not a plugin's -- from capabilities/proxy.json.
    let attributes = tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "connections_list",
            "connections_add",
            "connections_add_relay",
            "connections_remove",
            "connections_select",
            "connections_get_current",
            "open_external",
            "editors_list",
            "open_in_editor",
            "daemon_status",
            "daemon_install",
            "daemon_update",
            "daemon_restart",
            "take_over_daemon",
            "connection_version",
            "window_ready",
            "window_set_theme",
        ]),
    );
    tauri_build::try_build(attributes).expect("smind desktop: tauri_build::try_build failed");
}
