fn main() {
    // AC5/AC6: the connection-picker/open-external commands get
    // autogenerated `allow-*`/`deny-*` permissions
    // (desktop/src-tauri/permissions/autogenerated/, gitignored, rebuilt
    // every build), referenced -- unprefixed, since they're app
    // commands, not a plugin's -- from capabilities/proxy.json.
    let attributes = tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "connections_list",
            "connections_add",
            "connections_add_relay",
            "connections_remove",
            "connections_select",
            "connections_get_current",
            "open_external",
            "daemon_status",
            "daemon_install",
            "daemon_update",
            "daemon_restart",
            "take_over_daemon",
            "connection_version",
        ]),
    );
    tauri_build::try_build(attributes).expect("smind desktop: tauri_build::try_build failed");
}
