// relay.proto — smind relay wire contract (daemon ↔ relay, ADR-0007 (f)).
//
// The relay is a dumb pipe: it authenticates connections (ADR-0011) and
// forwards opaque ciphertext frames between a daemon and its paired mobile
// devices. It never sees an E2EE session key and cannot inspect Frame
// payloads.
//
// Control/data socket mapping (ADR-0007 (b), decided here as the ADR left
// it to this plan):
//
//   - Control socket  -> OpenControl, one bidi stream per daemon↔relay
//     connection. It owns connection/session lifecycle: device attach and
//     detach announcements, liveness, and (later) buffer/ack bookkeeping.
//     It carries no application payload.
//   - Data socket     -> OpenData, one bidi stream per paired device per
//     E2EE session — opened by the daemon for each device and by the mobile
//     device itself, so fanout is "one stream per device" rather than a
//     shared pipe needing multiplexing. Each Frame is a self-contained
//     envelope (routing metadata + opaque ciphertext), which is also what
//     the reconnect buffer (ADR-0007 (a)) stores and flushes on reconnect.
//
// A single multiplexed stream carrying a tagged envelope for both control
// and data was considered and rejected: it reintroduces exactly the ad hoc
// multiplexing the control/data split exists to avoid, and control liveness
// would then share flow control with bulk ciphertext.
//
// Relay admission (ADR-0011) is deliberately unary and separate from both
// streams: AdmitChallenge issues a server nonce, then Admit carries the
// daemon's HMAC over the transcript (protocol version, workspace ID, both
// nonces, daemon key ID). The raw workspace secret never appears on the
// wire. A connection is bound to one workspace; Frames whose workspace or
// session ID mismatch the binding are rejected by the relay implementation
// (not the wire contract). Admission is independent of the E2EE handshake,
// which happens inside the encrypted payload the relay forwards blindly.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: internal/relay/relaypb/relay.proto

package relaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Relay_AdmitChallenge_FullMethodName = "/relay.v1.Relay/AdmitChallenge"
	Relay_Admit_FullMethodName          = "/relay.v1.Relay/Admit"
	Relay_OpenControl_FullMethodName    = "/relay.v1.Relay/OpenControl"
	Relay_OpenData_FullMethodName       = "/relay.v1.Relay/OpenData"
)

// RelayClient is the client API for Relay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RelayClient interface {
	// Step 1 of admission: the daemon requests a server nonce for the
	// challenge transcript. Unknown workspace IDs are answered with a nonce
	// anyway (verification happens in Admit) to avoid an oracle for which
	// workspaces exist.
	AdmitChallenge(ctx context.Context, in *AdmitChallengeRequest, opts ...grpc.CallOption) (*AdmitChallengeResponse, error)
	// Step 2 of admission: the daemon proves possession of the workspace
	// secret via HMAC-SHA256 over the transcript (protocol version,
	// workspace_id, client nonce, server nonce, daemon key ID). On success
	// the relay binds the connection's gRPC context to that workspace.
	Admit(ctx context.Context, in *AdmitRequest, opts ...grpc.CallOption) (*AdmitResponse, error)
	// Control socket (ADR-0007 (b)): one persistent bidi stream per daemon.
	// Session and device lifecycle only — never application payload.
	OpenControl(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlFrame, ControlFrame], error)
	// Data socket (ADR-0007 (b)): one bidi stream per paired device,
	// carrying opaque ciphertext envelopes both directions. The relay
	// forwards, buffers (bounded), and evicts; it never decrypts.
	OpenData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Frame, Frame], error)
}

type relayClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayClient(cc grpc.ClientConnInterface) RelayClient {
	return &relayClient{cc}
}

func (c *relayClient) AdmitChallenge(ctx context.Context, in *AdmitChallengeRequest, opts ...grpc.CallOption) (*AdmitChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdmitChallengeResponse)
	err := c.cc.Invoke(ctx, Relay_AdmitChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClient) Admit(ctx context.Context, in *AdmitRequest, opts ...grpc.CallOption) (*AdmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdmitResponse)
	err := c.cc.Invoke(ctx, Relay_Admit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClient) OpenControl(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlFrame, ControlFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Relay_ServiceDesc.Streams[0], Relay_OpenControl_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ControlFrame, ControlFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Relay_OpenControlClient = grpc.BidiStreamingClient[ControlFrame, ControlFrame]

func (c *relayClient) OpenData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Frame, Frame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Relay_ServiceDesc.Streams[1], Relay_OpenData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Frame, Frame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Relay_OpenDataClient = grpc.BidiStreamingClient[Frame, Frame]

// RelayServer is the server API for Relay service.
// All implementations must embed UnimplementedRelayServer
// for forward compatibility.
type RelayServer interface {
	// Step 1 of admission: the daemon requests a server nonce for the
	// challenge transcript. Unknown workspace IDs are answered with a nonce
	// anyway (verification happens in Admit) to avoid an oracle for which
	// workspaces exist.
	AdmitChallenge(context.Context, *AdmitChallengeRequest) (*AdmitChallengeResponse, error)
	// Step 2 of admission: the daemon proves possession of the workspace
	// secret via HMAC-SHA256 over the transcript (protocol version,
	// workspace_id, client nonce, server nonce, daemon key ID). On success
	// the relay binds the connection's gRPC context to that workspace.
	Admit(context.Context, *AdmitRequest) (*AdmitResponse, error)
	// Control socket (ADR-0007 (b)): one persistent bidi stream per daemon.
	// Session and device lifecycle only — never application payload.
	OpenControl(grpc.BidiStreamingServer[ControlFrame, ControlFrame]) error
	// Data socket (ADR-0007 (b)): one bidi stream per paired device,
	// carrying opaque ciphertext envelopes both directions. The relay
	// forwards, buffers (bounded), and evicts; it never decrypts.
	OpenData(grpc.BidiStreamingServer[Frame, Frame]) error
	mustEmbedUnimplementedRelayServer()
}

// UnimplementedRelayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelayServer struct{}

func (UnimplementedRelayServer) AdmitChallenge(context.Context, *AdmitChallengeRequest) (*AdmitChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdmitChallenge not implemented")
}
func (UnimplementedRelayServer) Admit(context.Context, *AdmitRequest) (*AdmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Admit not implemented")
}
func (UnimplementedRelayServer) OpenControl(grpc.BidiStreamingServer[ControlFrame, ControlFrame]) error {
	return status.Error(codes.Unimplemented, "method OpenControl not implemented")
}
func (UnimplementedRelayServer) OpenData(grpc.BidiStreamingServer[Frame, Frame]) error {
	return status.Error(codes.Unimplemented, "method OpenData not implemented")
}
func (UnimplementedRelayServer) mustEmbedUnimplementedRelayServer() {}
func (UnimplementedRelayServer) testEmbeddedByValue()               {}

// UnsafeRelayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayServer will
// result in compilation errors.
type UnsafeRelayServer interface {
	mustEmbedUnimplementedRelayServer()
}

func RegisterRelayServer(s grpc.ServiceRegistrar, srv RelayServer) {
	// If the following call panics, it indicates UnimplementedRelayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Relay_ServiceDesc, srv)
}

func _Relay_AdmitChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdmitChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServer).AdmitChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Relay_AdmitChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServer).AdmitChallenge(ctx, req.(*AdmitChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Relay_Admit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServer).Admit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Relay_Admit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServer).Admit(ctx, req.(*AdmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Relay_OpenControl_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RelayServer).OpenControl(&grpc.GenericServerStream[ControlFrame, ControlFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Relay_OpenControlServer = grpc.BidiStreamingServer[ControlFrame, ControlFrame]

func _Relay_OpenData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RelayServer).OpenData(&grpc.GenericServerStream[Frame, Frame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Relay_OpenDataServer = grpc.BidiStreamingServer[Frame, Frame]

// Relay_ServiceDesc is the grpc.ServiceDesc for Relay service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Relay_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "relay.v1.Relay",
	HandlerType: (*RelayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdmitChallenge",
			Handler:    _Relay_AdmitChallenge_Handler,
		},
		{
			MethodName: "Admit",
			Handler:    _Relay_Admit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenControl",
			Handler:       _Relay_OpenControl_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "OpenData",
			Handler:       _Relay_OpenData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/relay/relaypb/relay.proto",
}
