// relay.proto — smind relay wire contract (daemon ↔ relay, ADR-0007 (f)).
//
// The relay is a dumb pipe: it authenticates connections (ADR-0011) and
// forwards opaque ciphertext frames between a daemon and its paired mobile
// devices. It never sees an E2EE session key and cannot inspect Frame
// payloads.
//
// Control/data socket mapping (ADR-0007 (b), decided here as the ADR left
// it to this plan):
//
//   - Control socket  -> OpenControl, one bidi stream per daemon↔relay
//     connection. It owns connection/session lifecycle: device attach and
//     detach announcements, liveness, and (later) buffer/ack bookkeeping.
//     It carries no application payload.
//   - Data socket     -> OpenData, one bidi stream per paired device per
//     E2EE session — opened by the daemon for each device and by the mobile
//     device itself, so fanout is "one stream per device" rather than a
//     shared pipe needing multiplexing. Each Frame is a self-contained
//     envelope (routing metadata + opaque ciphertext), which is also what
//     the reconnect buffer (ADR-0007 (a)) stores and flushes on reconnect.
//
// A single multiplexed stream carrying a tagged envelope for both control
// and data was considered and rejected: it reintroduces exactly the ad hoc
// multiplexing the control/data split exists to avoid, and control liveness
// would then share flow control with bulk ciphertext.
//
// Relay admission (ADR-0011) is deliberately unary and separate from both
// streams: AdmitChallenge issues a server nonce, then Admit carries the
// daemon's HMAC over the transcript (protocol version, workspace ID, both
// nonces, daemon key ID). The raw workspace secret never appears on the
// wire. A connection is bound to one workspace; Frames whose workspace or
// session ID mismatch the binding are rejected by the relay implementation
// (not the wire contract). Admission is independent of the E2EE handshake,
// which happens inside the encrypted payload the relay forwards blindly.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: internal/relay/relaypb/relay.proto

package relaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Direction of a frame's travel. The relay uses it (with session_id) to
// route and to enforce the authenticated workspace binding; the E2EE
// session's own directional keys (see internal/relay/e2ee) make a frame
// unusable in the wrong direction regardless.
type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	// Daemon -> device.
	Direction_DIRECTION_DAEMON_TO_DEVICE Direction = 1
	// Device -> daemon.
	Direction_DIRECTION_DEVICE_TO_DAEMON Direction = 2
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_DAEMON_TO_DEVICE",
		2: "DIRECTION_DEVICE_TO_DAEMON",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED":      0,
		"DIRECTION_DAEMON_TO_DEVICE": 1,
		"DIRECTION_DEVICE_TO_DAEMON": 2,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_relay_relaypb_relay_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_internal_relay_relaypb_relay_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_internal_relay_relaypb_relay_proto_rawDescGZIP(), []int{0}
}

type AdmitChallengeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol version of the admission state machine (v1 = 1).
	ProtocolVersion uint32 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Workspace the connection wants to be bound to.
	WorkspaceId string `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// Fresh random nonce generated by the daemon for this transcript.
	ClientNonce []byte `protobuf:"bytes,3,opt,name=client_nonce,json=clientNonce,proto3" json:"client_nonce,omitempty"`
	// Stable identifier of the daemon's persisted keypair (ADR-0007 (g)).
	DaemonKeyId   string `protobuf:"bytes,4,opt,name=daemon_key_id,json=daemonKeyId,proto3" json:"daemon_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmitChallengeRequest) Reset() {
	*x = AdmitChallengeRequest{}
	mi := &file_internal_relay_relaypb_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmitChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmitChallengeRequest) ProtoMessage() {}

func (x *AdmitChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relay_relaypb_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmitChallengeRequest.ProtoReflect.Descriptor instead.
func (*AdmitChallengeRequest) Descriptor() ([]byte, []int) {
	return file_internal_relay_relaypb_relay_proto_rawDescGZIP(), []int{0}
}

func (x *AdmitChallengeRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *AdmitChallengeRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *AdmitChallengeRequest) GetClientNonce() []byte {
	if x != nil {
		return x.ClientNonce
	}
	return nil
}

func (x *AdmitChallengeRequest) GetDaemonKeyId() string {
	if x != nil {
		return x.DaemonKeyId
	}
	return ""
}

type AdmitChallengeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fresh random nonce generated by the relay for this transcript. May be
	// issued even for unknown workspaces; see AdmitChallenge.
	ServerNonce   []byte `protobuf:"bytes,1,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmitChallengeResponse) Reset() {
	*x = AdmitChallengeResponse{}
	mi := &file_internal_relay_relaypb_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmitChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmitChallengeResponse) ProtoMessage() {}

func (x *AdmitChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relay_relaypb_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmitChallengeResponse.ProtoReflect.Descriptor instead.
func (*AdmitChallengeResponse) Descriptor() ([]byte, []int) {
	return file_internal_relay_relaypb_relay_proto_rawDescGZIP(), []int{1}
}

func (x *AdmitChallengeResponse) GetServerNonce() []byte {
	if x != nil {
		return x.ServerNonce
	}
	return nil
}

type AdmitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Same values as the AdmitChallengeRequest that obtained the nonce.
	ProtocolVersion uint32 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	WorkspaceId     string `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ClientNonce     []byte `protobuf:"bytes,3,opt,name=client_nonce,json=clientNonce,proto3" json:"client_nonce,omitempty"`
	DaemonKeyId     string `protobuf:"bytes,4,opt,name=daemon_key_id,json=daemonKeyId,proto3" json:"daemon_key_id,omitempty"`
	ServerNonce     []byte `protobuf:"bytes,5,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	// HMAC-SHA256(workspace_secret, protocol_version || workspace_id ||
	// client_nonce || server_nonce || daemon_key_id) with a fixed canonical
	// concatenation defined by the relay implementation. The secret itself is
	// never sent.
	Hmac          []byte `protobuf:"bytes,6,opt,name=hmac,proto3" json:"hmac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmitRequest) Reset() {
	*x = AdmitRequest{}
	mi := &file_internal_relay_relaypb_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmitRequest) ProtoMessage() {}

func (x *AdmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relay_relaypb_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmitRequest.ProtoReflect.Descriptor instead.
func (*AdmitRequest) Descriptor() ([]byte, []int) {
	return file_internal_relay_relaypb_relay_proto_rawDescGZIP(), []int{2}
}

func (x *AdmitRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *AdmitRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *AdmitRequest) GetClientNonce() []byte {
	if x != nil {
		return x.ClientNonce
	}
	return nil
}

func (x *AdmitRequest) GetDaemonKeyId() string {
	if x != nil {
		return x.DaemonKeyId
	}
	return ""
}

func (x *AdmitRequest) GetServerNonce() []byte {
	if x != nil {
		return x.ServerNonce
	}
	return nil
}

func (x *AdmitRequest) GetHmac() []byte {
	if x != nil {
		return x.Hmac
	}
	return nil
}

type AdmitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque handle naming the admitted (workspace-bound) session context;
	// presented on subsequent streams. Not a credential — streams are still
	// bound to the workspace by the admission on their connection.
	AdmissionId   []byte `protobuf:"bytes,1,opt,name=admission_id,json=admissionId,proto3" json:"admission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmitResponse) Reset() {
	*x = AdmitResponse{}
	mi := &file_internal_relay_relaypb_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmitResponse) ProtoMessage() {}

func (x *AdmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relay_relaypb_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmitResponse.ProtoReflect.Descriptor instead.
func (*AdmitResponse) Descriptor() ([]byte, []int) {
	return file_internal_relay_relaypb_relay_proto_rawDescGZIP(), []int{3}
}

func (x *AdmitResponse) GetAdmissionId() []byte {
	if x != nil {
		return x.AdmissionId
	}
	return nil
}

type ControlFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Workspace the control connection is bound to; must match the
	// authenticated admission binding or the relay rejects the stream.
	WorkspaceId string `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*ControlFrame_DeviceAttach_
	//	*ControlFrame_DeviceDetach_
	//	*ControlFrame_Ping_
	//	*ControlFrame_Pong_
	Body          isControlFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlFrame) Reset() {
	*x = ControlFrame{}
	mi := &file_internal_relay_relaypb_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlFrame) ProtoMessage() {}

func (x *ControlFrame) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relay_relaypb_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlFrame.ProtoReflect.Descriptor instead.
func (*ControlFrame) Descriptor() ([]byte, []int) {
	return file_internal_relay_relaypb_relay_proto_rawDescGZIP(), []int{4}
}

func (x *ControlFrame) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ControlFrame) GetBody() isControlFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ControlFrame) GetDeviceAttach() *ControlFrame_DeviceAttach {
	if x != nil {
		if x, ok := x.Body.(*ControlFrame_DeviceAttach_); ok {
			return x.DeviceAttach
		}
	}
	return nil
}

func (x *ControlFrame) GetDeviceDetach() *ControlFrame_DeviceDetach {
	if x != nil {
		if x, ok := x.Body.(*ControlFrame_DeviceDetach_); ok {
			return x.DeviceDetach
		}
	}
	return nil
}

func (x *ControlFrame) GetPing() *ControlFrame_Ping {
	if x != nil {
		if x, ok := x.Body.(*ControlFrame_Ping_); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ControlFrame) GetPong() *ControlFrame_Pong {
	if x != nil {
		if x, ok := x.Body.(*ControlFrame_Pong_); ok {
			return x.Pong
		}
	}
	return nil
}

type isControlFrame_Body interface {
	isControlFrame_Body()
}

type ControlFrame_DeviceAttach_ struct {
	DeviceAttach *ControlFrame_DeviceAttach `protobuf:"bytes,2,opt,name=device_attach,json=deviceAttach,proto3,oneof"`
}

type ControlFrame_DeviceDetach_ struct {
	DeviceDetach *ControlFrame_DeviceDetach `protobuf:"bytes,3,opt,name=device_detach,json=deviceDetach,proto3,oneof"`
}

type ControlFrame_Ping_ struct {
	Ping *ControlFrame_Ping `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

type ControlFrame_Pong_ struct {
	Pong *ControlFrame_Pong `protobuf:"bytes,5,opt,name=pong,proto3,oneof"`
}

func (*ControlFrame_DeviceAttach_) isControlFrame_Body() {}

func (*ControlFrame_DeviceDetach_) isControlFrame_Body() {}

func (*ControlFrame_Ping_) isControlFrame_Body() {}

func (*ControlFrame_Pong_) isControlFrame_Body() {}

// Frame is the envelope the relay stores, buffers, and forwards. Payload
// is opaque ciphertext (E2EE-wrapped application or handshake bytes);
// sequence mirrors the E2EE per-direction counter (ADR-0007 (c)/(d)) so the
// relay can order buffered frames on flush.
type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Workspace binding; must match the connection's admitted workspace.
	WorkspaceId string `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// E2EE session identifier (fresh per handshake, ADR-0007 (e)).
	SessionId []byte `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Paired device this frame is routed to/from.
	DeviceId string `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Direction of travel, for routing and binding enforcement.
	Direction Direction `protobuf:"varint,4,opt,name=direction,proto3,enum=relay.v1.Direction" json:"direction,omitempty"`
	// Per-direction monotonic counter from the E2EE session.
	Sequence uint64 `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Opaque ciphertext. The relay has no key for this and must not attempt
	// to inspect it.
	Payload       []byte `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_internal_relay_relaypb_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relay_relaypb_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_internal_relay_relaypb_relay_proto_rawDescGZIP(), []int{5}
}

func (x *Frame) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Frame) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *Frame) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Frame) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *Frame) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ControlFrame_DeviceAttach struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device ID assigned at pairing.
	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// The device's persisted public key material as offered at pairing,
	// opaque to the relay's control logic.
	PairingPayload []byte `protobuf:"bytes,2,opt,name=pairing_payload,json=pairingPayload,proto3" json:"pairing_payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ControlFrame_DeviceAttach) Reset() {
	*x = ControlFrame_DeviceAttach{}
	mi := &file_internal_relay_relaypb_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlFrame_DeviceAttach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlFrame_DeviceAttach) ProtoMessage() {}

func (x *ControlFrame_DeviceAttach) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relay_relaypb_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlFrame_DeviceAttach.ProtoReflect.Descriptor instead.
func (*ControlFrame_DeviceAttach) Descriptor() ([]byte, []int) {
	return file_internal_relay_relaypb_relay_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ControlFrame_DeviceAttach) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ControlFrame_DeviceAttach) GetPairingPayload() []byte {
	if x != nil {
		return x.PairingPayload
	}
	return nil
}

type ControlFrame_DeviceDetach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlFrame_DeviceDetach) Reset() {
	*x = ControlFrame_DeviceDetach{}
	mi := &file_internal_relay_relaypb_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlFrame_DeviceDetach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlFrame_DeviceDetach) ProtoMessage() {}

func (x *ControlFrame_DeviceDetach) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relay_relaypb_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlFrame_DeviceDetach.ProtoReflect.Descriptor instead.
func (*ControlFrame_DeviceDetach) Descriptor() ([]byte, []int) {
	return file_internal_relay_relaypb_relay_proto_rawDescGZIP(), []int{4, 1}
}

func (x *ControlFrame_DeviceDetach) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type ControlFrame_Ping struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonic control-sequence number for liveness/ordering.
	Sequence      uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlFrame_Ping) Reset() {
	*x = ControlFrame_Ping{}
	mi := &file_internal_relay_relaypb_relay_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlFrame_Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlFrame_Ping) ProtoMessage() {}

func (x *ControlFrame_Ping) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relay_relaypb_relay_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlFrame_Ping.ProtoReflect.Descriptor instead.
func (*ControlFrame_Ping) Descriptor() ([]byte, []int) {
	return file_internal_relay_relaypb_relay_proto_rawDescGZIP(), []int{4, 2}
}

func (x *ControlFrame_Ping) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type ControlFrame_Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlFrame_Pong) Reset() {
	*x = ControlFrame_Pong{}
	mi := &file_internal_relay_relaypb_relay_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlFrame_Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlFrame_Pong) ProtoMessage() {}

func (x *ControlFrame_Pong) ProtoReflect() protoreflect.Message {
	mi := &file_internal_relay_relaypb_relay_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlFrame_Pong.ProtoReflect.Descriptor instead.
func (*ControlFrame_Pong) Descriptor() ([]byte, []int) {
	return file_internal_relay_relaypb_relay_proto_rawDescGZIP(), []int{4, 3}
}

func (x *ControlFrame_Pong) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_internal_relay_relaypb_relay_proto protoreflect.FileDescriptor

const file_internal_relay_relaypb_relay_proto_rawDesc = "" +
	"\n" +
	"\"internal/relay/relaypb/relay.proto\x12\brelay.v1\"\xac\x01\n" +
	"\x15AdmitChallengeRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12!\n" +
	"\fclient_nonce\x18\x03 \x01(\fR\vclientNonce\x12\"\n" +
	"\rdaemon_key_id\x18\x04 \x01(\tR\vdaemonKeyId\";\n" +
	"\x16AdmitChallengeResponse\x12!\n" +
	"\fserver_nonce\x18\x01 \x01(\fR\vserverNonce\"\xda\x01\n" +
	"\fAdmitRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12!\n" +
	"\fclient_nonce\x18\x03 \x01(\fR\vclientNonce\x12\"\n" +
	"\rdaemon_key_id\x18\x04 \x01(\tR\vdaemonKeyId\x12!\n" +
	"\fserver_nonce\x18\x05 \x01(\fR\vserverNonce\x12\x12\n" +
	"\x04hmac\x18\x06 \x01(\fR\x04hmac\"2\n" +
	"\rAdmitResponse\x12!\n" +
	"\fadmission_id\x18\x01 \x01(\fR\vadmissionId\"\x82\x04\n" +
	"\fControlFrame\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12J\n" +
	"\rdevice_attach\x18\x02 \x01(\v2#.relay.v1.ControlFrame.DeviceAttachH\x00R\fdeviceAttach\x12J\n" +
	"\rdevice_detach\x18\x03 \x01(\v2#.relay.v1.ControlFrame.DeviceDetachH\x00R\fdeviceDetach\x121\n" +
	"\x04ping\x18\x04 \x01(\v2\x1b.relay.v1.ControlFrame.PingH\x00R\x04ping\x121\n" +
	"\x04pong\x18\x05 \x01(\v2\x1b.relay.v1.ControlFrame.PongH\x00R\x04pong\x1aT\n" +
	"\fDeviceAttach\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12'\n" +
	"\x0fpairing_payload\x18\x02 \x01(\fR\x0epairingPayload\x1a+\n" +
	"\fDeviceDetach\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x1a\"\n" +
	"\x04Ping\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x1a\"\n" +
	"\x04Pong\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequenceB\x06\n" +
	"\x04body\"\xcf\x01\n" +
	"\x05Frame\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\fR\tsessionId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x121\n" +
	"\tdirection\x18\x04 \x01(\x0e2\x13.relay.v1.DirectionR\tdirection\x12\x1a\n" +
	"\bsequence\x18\x05 \x01(\x04R\bsequence\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload*f\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aDIRECTION_DAEMON_TO_DEVICE\x10\x01\x12\x1e\n" +
	"\x1aDIRECTION_DEVICE_TO_DAEMON\x10\x022\x8b\x02\n" +
	"\x05Relay\x12S\n" +
	"\x0eAdmitChallenge\x12\x1f.relay.v1.AdmitChallengeRequest\x1a .relay.v1.AdmitChallengeResponse\x128\n" +
	"\x05Admit\x12\x16.relay.v1.AdmitRequest\x1a\x17.relay.v1.AdmitResponse\x12A\n" +
	"\vOpenControl\x12\x16.relay.v1.ControlFrame\x1a\x16.relay.v1.ControlFrame(\x010\x01\x120\n" +
	"\bOpenData\x12\x0f.relay.v1.Frame\x1a\x0f.relay.v1.Frame(\x010\x01B5Z3github.com/spacingmind/smind/internal/relay/relaypbb\x06proto3"

var (
	file_internal_relay_relaypb_relay_proto_rawDescOnce sync.Once
	file_internal_relay_relaypb_relay_proto_rawDescData []byte
)

func file_internal_relay_relaypb_relay_proto_rawDescGZIP() []byte {
	file_internal_relay_relaypb_relay_proto_rawDescOnce.Do(func() {
		file_internal_relay_relaypb_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_relay_relaypb_relay_proto_rawDesc), len(file_internal_relay_relaypb_relay_proto_rawDesc)))
	})
	return file_internal_relay_relaypb_relay_proto_rawDescData
}

var file_internal_relay_relaypb_relay_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_relay_relaypb_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_relay_relaypb_relay_proto_goTypes = []any{
	(Direction)(0),                    // 0: relay.v1.Direction
	(*AdmitChallengeRequest)(nil),     // 1: relay.v1.AdmitChallengeRequest
	(*AdmitChallengeResponse)(nil),    // 2: relay.v1.AdmitChallengeResponse
	(*AdmitRequest)(nil),              // 3: relay.v1.AdmitRequest
	(*AdmitResponse)(nil),             // 4: relay.v1.AdmitResponse
	(*ControlFrame)(nil),              // 5: relay.v1.ControlFrame
	(*Frame)(nil),                     // 6: relay.v1.Frame
	(*ControlFrame_DeviceAttach)(nil), // 7: relay.v1.ControlFrame.DeviceAttach
	(*ControlFrame_DeviceDetach)(nil), // 8: relay.v1.ControlFrame.DeviceDetach
	(*ControlFrame_Ping)(nil),         // 9: relay.v1.ControlFrame.Ping
	(*ControlFrame_Pong)(nil),         // 10: relay.v1.ControlFrame.Pong
}
var file_internal_relay_relaypb_relay_proto_depIdxs = []int32{
	7,  // 0: relay.v1.ControlFrame.device_attach:type_name -> relay.v1.ControlFrame.DeviceAttach
	8,  // 1: relay.v1.ControlFrame.device_detach:type_name -> relay.v1.ControlFrame.DeviceDetach
	9,  // 2: relay.v1.ControlFrame.ping:type_name -> relay.v1.ControlFrame.Ping
	10, // 3: relay.v1.ControlFrame.pong:type_name -> relay.v1.ControlFrame.Pong
	0,  // 4: relay.v1.Frame.direction:type_name -> relay.v1.Direction
	1,  // 5: relay.v1.Relay.AdmitChallenge:input_type -> relay.v1.AdmitChallengeRequest
	3,  // 6: relay.v1.Relay.Admit:input_type -> relay.v1.AdmitRequest
	5,  // 7: relay.v1.Relay.OpenControl:input_type -> relay.v1.ControlFrame
	6,  // 8: relay.v1.Relay.OpenData:input_type -> relay.v1.Frame
	2,  // 9: relay.v1.Relay.AdmitChallenge:output_type -> relay.v1.AdmitChallengeResponse
	4,  // 10: relay.v1.Relay.Admit:output_type -> relay.v1.AdmitResponse
	5,  // 11: relay.v1.Relay.OpenControl:output_type -> relay.v1.ControlFrame
	6,  // 12: relay.v1.Relay.OpenData:output_type -> relay.v1.Frame
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_internal_relay_relaypb_relay_proto_init() }
func file_internal_relay_relaypb_relay_proto_init() {
	if File_internal_relay_relaypb_relay_proto != nil {
		return
	}
	file_internal_relay_relaypb_relay_proto_msgTypes[4].OneofWrappers = []any{
		(*ControlFrame_DeviceAttach_)(nil),
		(*ControlFrame_DeviceDetach_)(nil),
		(*ControlFrame_Ping_)(nil),
		(*ControlFrame_Pong_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_relay_relaypb_relay_proto_rawDesc), len(file_internal_relay_relaypb_relay_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_relay_relaypb_relay_proto_goTypes,
		DependencyIndexes: file_internal_relay_relaypb_relay_proto_depIdxs,
		EnumInfos:         file_internal_relay_relaypb_relay_proto_enumTypes,
		MessageInfos:      file_internal_relay_relaypb_relay_proto_msgTypes,
	}.Build()
	File_internal_relay_relaypb_relay_proto = out.File
	file_internal_relay_relaypb_relay_proto_goTypes = nil
	file_internal_relay_relaypb_relay_proto_depIdxs = nil
}
